---
  - hosts: local
    connection: local
    gather_facts: False
    vars:
      instance_type: t2.micro
      security_group: dns_sg
      image: ami-0520e698dd500b1d1
      keypair: VPN
      region: us-east-2
      vpc: vpc-0e29420e07010d826
      vpc_subnet_id: subnet-07c8e9cd2fe24ffc2
      count: 1
    vars_files:
      - aws_keys.yml

    tasks:
      - name: Create Security Group
        ec2_group:
          name: "{{ security_group }}"
          description: DNS C2 Security Group
          region: "{{ region }}"
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
          rules:
           - proto: tcp
             from_port: 22
             to_port: 22
             cidr_ip: 0.0.0.0/0
           - proto: udp
             from_port: 53
             to_port: 53
             cidr_ip: 0.0.0.0/0
           - proto: tcp
             from_port: 53
             to_port: 53
             cidr_ip: 0.0.0.0/0
          rules_egress:
           - proto: all
             cidr_ip: 0.0.0.0/0

      - name: Launch New EC2 Instance
        ec2:
           aws_access_key: "{{ aws_access_key }}"
           aws_secret_key: "{{ aws_secret_key }}"
           group: "{{ security_group }}"
           instance_type: "{{ instance_type }}"
           image: "{{ image }}"
           wait: true 
           region: "{{ region }}"
           keypair: "{{ keypair }}"
           count: "{{ count }}"
           count_tag:
             Name: DNS_Server
        register: ec2

      - name: Add Newly Created Host to Hosts List
        add_host:
          name: "{{ item.public_ip }}"
          groups: dns_servers
        with_items: "{{ ec2.instances }}"

      - name: Wait for SSH Service to Start
        wait_for:
          host: "{{ item.public_ip }}"
          port: 22 
          state: started 
        with_items: "{{ ec2.instances }}"

  - hosts: dns_servers
    remote_user: ec2-user
    become: yes
    gather_facts: no
    pre_tasks:
     - name: 'Initialize Repos and Update Packages'
       raw: 'sudo yum -y update' 
       raw: 'sudo yum -y install python3-pip git'
    tasks:
     - name: Stop Resolved Service
       systemd:
         state: stopped
         enabled: no
         name: systemd-resolved.service
     - name: Change Hostname
       hostname:
         name: ns1
     - name: Install BIND Server
       yum:
         name: bind-chroot
         state: latest
     - name: Copy BIND Config
       copy:
         src: named.conf
         dest: /etc/named.conf
         owner: root
         group: root
         mode: '0664'
     - name: Copy Local Zone Conf File
       copy:
         src: named.conf.local
         dest: /etc/named/named.conf.local
         owner: root
         group: root
         mode: '0664'
     - name: Create Zones Directory
       file:
         path: /etc/named/zones
         state: directory       
     - name: Copy Local Zone Conf File
       copy:
        src: db.exploderbot-uah.com
        dest: /etc/named/zones/db.exploderbot-uah.com
        owner: root
        group: root
        mode: '0664'    
     - name: Start Named Service
       systemd:
         state: started
         enabled: yes
         name: named  
     - name: Download Wireshark
       yum:
         name: wireshark
         state: latest
     - name: Create PCAP Service Account
       user:
         name: pcap_svc
         shell: /usr/sbin/nologin
         uid: 250
         group: wireshark
     - name: Write Packet Capture Script
       copy:
         src: packetcap.sh 
         dest: /usr/local/bin/packetcap.sh
         mode: '0400'
         owner: pcap_svc
         group: wireshark
     - name: Write Packet Capture Service
       copy:
         src: dnscap.service
         dest: /usr/lib/systemd/system/dnscap.service
         owner: root
         group: root
     - name: Start DNS Capture Service
       systemd:
         state: started
         enabled: yes
         name: dnscap.service 


